### ISSUE TITLE
Show # of contributors at bottom of demo page

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#10]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

It's tough to quickly count the # of contributors!

## Solution

The demo page is at /index.html, and we ought to be able to add a line around here:

https://github.com/publiclab/community-toolbox/blob/master/index.html#L112-L114

to insert the # of contributors into the `h2` title, so it reads:

`Contributors (100)` (for example, if there were 100 contributors)

We'd love help with this one!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by maya-shankar** [comment]
I'd like to work on this!

**Comment by jywarren** [comment]
We'd love it if you did! Thank you, and we're here to help!

**Comment by ijajmulani** [comment]
@maya-shankar Can I help you? I also want to contribute.

**Comment by GeoBlaso** [comment]
Is it still open? Can I contribute somehow?

**Comment by jywarren** [comment]
Oh, yes please! We'd love some help with this.

**Comment by jywarren** [comment]
Anyone want to take a crack at this and need some help? Thanks!

**Comment by nikramakrishnan** [comment]
Because there hasn't been a response in a while, I would like to try this out.

**Comment by jywarren** [comment]
That would be great -- we'd love your help!

**Comment by jywarren** [comment]
Hi, it should be the total, and I wonder if we now have more than 100
contributors and are not seeing everyone on the page? Our project has been
growing and I think this may now be a bug. What do u think?

**Comment by nikramakrishnan** [comment]
@jywarren What do you think should be done?

**Comment by jywarren** [comment]
Sorry for slow reply! Reading through this now, thank you!

**Comment by jywarren** [comment]
Hmm, well, let's consider adding that feature over there; if not, we can add the code here and migrate it upstream later. I opened an issue: https://github.com/MichielvdVelde/github-api-simple/issues/5 and we'll see -- i also linked to an implementation via the Ubsersicht project:

https://github.com/espy/ubersicht/blob/551aced0bd3157ed7811b6380fdaa8c10b9d6e26/script/main.js#L169-L184

Would you like to give implementation along those lines a try? Either in this repository or upstream in a PR for `github-api-simple`, if they're willing?

**Comment by nikramakrishnan** [comment]
I've implemented paging without modifying `github-api-simple`, by getting headers, parsing, and getting all the pages.
The only problem/concern is that the pages will be ordered randomly on the page, because of the asynchronous nature of promises. (is there a way to fix this?)

Please suggest changes/improvements if any.

**Comment by jywarren** [comment]
Oh wow, can you open a pull request for this? Thank you!!!
