### ISSUE TITLE
Unlinked Recent  Contributors images and their Names [no hover effect]

### ISSUE THREAD

**Issue by subhahu123** [publiclab/community-toolbox#103]
### Please describe the problem (or idea)
NO Hover effect when cursor goes on their images 
##gif
![peek 2018-11-14 14-18](https://user-images.githubusercontent.com/34541684/48470759-49cf9480-e818-11e8-9daf-706afbec7cf0.gif)
image are not linked to their github profile
we can only see images of recent contributor ........but should also link to their profile
Nor the their contributor names are linked to their github profile 
if someone want to see their profile they have to search them by their user name

**Comment by subhahu123** [comment]
@jywarren review this
@Rishabh570

**Comment by Rishabh570** [comment]
@subhahu123 Hmm...would you like to this up?

**Comment by jywarren** [comment]
Hmm, yes i noticed this today. Let's see why this is happening!

**Comment by jywarren** [comment]
Is this linked to https://github.com/publiclab/community-toolbox/issues/75 ?

**Comment by Rishabh570** [comment]
@jywarren Nope, #75 is only for the list of contributors that show up on multi-repo view...

**Comment by lakshyabatman** [comment]
Is anyone taking this issue or I start working out on it?

**Comment by Rishabh570** [comment]
@lakshyabatman Your PR is merged, right?

**Comment by lakshyabatman** [comment]
No, I haven't submitted any PR on it, if anyone is not applying I'll start working on it.

**Comment by lakshyabatman** [comment]
Yes, but commented on this before merging.

**Comment by Rishabh570** [comment]
Your recent PR is merged which resolves this I guess? [this](https://github.com/publiclab/community-toolbox/pull/111), I guess this should be closed now...

**Comment by lakshyabatman** [comment]
This PR, is for image of recent contributors as well the name of them.
#75 , in this PR in which I contributed was for the names only not for their images.

**Comment by lakshyabatman** [comment]
I'm submitting an PR, the images will also have link to github profile as well it will work for monthly contributors as well. @Rishabh570 is it okay sir?

**Comment by lakshyabatman** [comment]
#124 , @Rishabh570 sir please check this.

**Comment by lakshyabatman** [comment]
@Rishabh570 this issue has been solved now.

**Comment by gauravano** [comment]
Hi @lakshyabatman thanks for notifying. Although, I have some suggestion regarding the UI of the page, which match this issue quite a bit, but I will open a new issue. Thanks all.
