### ISSUE TITLE
Add author thumbnail to issue display

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#108]
Thinking about the display on https://code.publiclab.org, we modeled it on GitHub's default style. But maybe we could do better?

![screen shot 2018-12-05 at 6 24 38 pm](https://user-images.githubusercontent.com/24359/49550904-35346880-f8bb-11e8-9760-9f24dc948120.png)

What if we did more to highlight the person posting the issue, since our community is so people centric? GitHub does this on the issue page, actually:

![image](https://user-images.githubusercontent.com/24359/49550943-52693700-f8bb-11e8-84e7-61a08741b6da.png)

Maybe it could look like this:

![image](https://user-images.githubusercontent.com/24359/49551137-0d91d000-f8bc-11e8-95d3-0b14ff97dc4a.png)

Is that not compact enough?

Hi @Rishabh570 i'm sorry i'm behind on replying to your issues!

**Comment by Rishabh570** [comment]
> What if we did more to highlight the person posting the issue, since our community is so people centric? 

Umm...this would be cool!

As an aside, we can show recent contributors' commits count on hover or something...and send an automated mail to thank the contributor of the week...just some thoughts ;)
What do you think about this? Obviously this is something to be done after MVC thing...

> i'm sorry i'm behind on replying to your issues!

@jywarren I understand :)

**Comment by jywarren** [comment]
yeah actually we can do a number of things -- i think GitHub shows a little
info popup for people now. Cool! And yes, after MVC!

**Comment by professionalzack** [comment]
Hello I would like to contribute. Specifically the "thumbnails" bit. Thanks !
