### ISSUE TITLE
Add list of authors of first-timers-only issues

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#13]
As people begin taking leadership in a project, they may start to post their own first timers only issues (see [this example](https://publiclab.github.io/community-toolbox/#r=all)). It'd be helpful to list these folks at the bottom of the page, so we know who's started to play this role. 

We could title the section "Welcomers" perhaps, say `These people have spent the time to create an issue specifically to welcome first timers:` and list their usernames!

**Comment by AnishRaj2000** [comment]
Hi can u help me solve this issue

**Comment by jywarren** [comment]
@Rishabh570 perhaps this one could be implemented similarly to the "recently active" list?

**Comment by Rishabh570** [comment]
Ohh...sorry for inactivity here, Yep this would be similar to that! I will take a look :)
