### ISSUE TITLE
Changing Contributors List UI To Bootstrap Card 

### ISSUE THREAD

**Issue by subhahu123** [publiclab/community-toolbox#150]
### Please describe the problem (or idea)

Currently view or the way website presents the list of contributors is very
Instead of that we can use bootstrap card for good view or desiging the lists of contributors

**Comment by jywarren** [comment]
Hi, maybe it'd be great to see this titled in a more positive way, like "Bootstrap Card UI for contributors list"? That way we're not making anyone feel bad about the design as it is. Thank you for your suggestion and we'd love to have help!

**Comment by subhahu123** [comment]
Sorry about this.... I will definately change it to .....

**Comment by jywarren** [comment]
no problem, and thanks!
