### ISSUE TITLE
Add "fork me on Github" ribbon to top corner

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#152]
I worry people don't know they can use this code for their own community! Let's add a ribbon in the top corner?

https://github.com/brookjordan/corner-ribbon

**Comment by jazdao** [comment]
Hi @jywarren, may I suggest [this](https://github.com/tholman/github-corners)? :)

**Comment by jywarren** [comment]
That'd be great! Are you interested in giving it a try? Thank you!

**Comment by jazdao** [comment]
Sure! Is there a particular page the banner should be on?

**Comment by jywarren** [comment]
Just the default `index.html` page in the root directory would be great!
Thank you!

**Comment by jazdao** [comment]
Hi @jywarren, could I ask for some input? Before I made any changes to the files, I tried to open the index.html page in a browser, but some of the resources failed to load:
![main](https://user-images.githubusercontent.com/22950070/54167436-e3a1f980-4426-11e9-8154-46b98aa9cb16.JPG)

I thought that it was an issue with my browser at first, but the same thing happened when I checked the [RawGit link](https://raw.githack.com/jazdao/community-toolbox/add-ribbon/index.html) for the branch. Do you know how I can fix this problem?

**Comment by rexagod** [comment]
Can you provide us a screenshot of the "networks" tab? Thanks!

**Comment by Rishabh570** [comment]
Hi @jazdao, are you still working on this? Please let me know if you need any help? Thanks!

**Comment by Rishabh570** [comment]
The PR regarding it is merged. Thanks!!! :+1:
