### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by avsingh999** [publiclab/community-toolbox#155]
### Please describe the problem (or idea)
I think if we can add a change theme button and the theme will be a toggle to the dark theme. It would be a better UI.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://code.publiclab.org/ 

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal @gauravano @publiclab/mentors what do you think about this please review if it's valid.
thanks : )

**Comment by gauravano** [comment]
We can try that :+1:

**Comment by Rishabh570** [comment]
Seems interesting! :+1:
