### ISSUE TITLE
[suggestion] Which MVC framework should be used  ??

### ISSUE THREAD

**Issue by subhahu123** [publiclab/community-toolbox#165]
#### Asking for suggestion

Which MVC framework should be used
`angular`, `react`, `ember` or simply `handlebars`

For angular framwork ( i m working on )
https://community-toolbox.stackblitz.io/   
https://github.com/publiclab/community-toolbox/pull/145 ( new changes )
( check this out )

Repo : https://github.com/subhahu123/mvc-community-toolbox

**Comment by subhahu123** [comment]
@HarshKhandeparkar  @gauravano  @publiclab/reviewers @publiclab/community-reps

**Comment by HarshKhandeparkar** [comment]
I would suggest react as it is simple(resembles with html), written in es6 and jsx which are the standards of the future (we might not have to compile react in the future) and it doesn't use any preprocessor like ts.

**Comment by subhahu123** [comment]
> I would suggest react as it is simple(resembles with html), written in es6 and jsx which are the standards of the future (we might not have to compile react in the future) and it doesn't use any preprocessor like ts.

i think we should use angular
react is more useful when data changes very frequently ( because it is totally dependent on redux ( flux ) )

**Comment by subhahu123** [comment]
> I would suggest react as it is simple(resembles with html), written in es6 and jsx which are the standards of the future (we might not have to compile react in the future) and it doesn't use any preprocessor like ts.

react is more known because of redux

**Comment by HarshKhandeparkar** [comment]
I think you are right. There is nothing that will change in real time here.

**Comment by subhahu123** [comment]
@HarshKhandeparkar So what should we use angular or etc

**Comment by HarshKhandeparkar** [comment]
Not sure really. I haven't seen this code much.

**Comment by HarshKhandeparkar** [comment]
I'm only a reviewer in image-sequencer

**Comment by subhahu123** [comment]
well then i think i should start working with angular ( for gsoc )
@HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Ok i guess. Well I'm 15 yrs old so i cannot tell you much. Ask other people who are familiar with this project.

**Comment by subhahu123** [comment]
@HarshKhandeparkar 
https://community-toolbox.stackblitz.io/
check this out ( build with angular framwork )
Not Yet Completed ............

**Comment by HarshKhandeparkar** [comment]
I checked it out. It's awesome!! A few suggestions:
- can you remove bots from the contributors list?
- can you display two contributors instead of one on a single row? You will then be sble to fit more contributors.

**Comment by HarshKhandeparkar** [comment]
I deleted your comment in image-sequencer

**Comment by Harshithpabbati** [comment]
It's really nice. Great work @subhahu123

**Comment by subhahu123** [comment]
@Harshithpabbati  @HarshKhandeparkar  https://community-toolbox-kiwxvw.stackblitz.io/
check this again i have added something ........

**Comment by subhahu123** [comment]
> * can you display two contributors instead of one on a single row? You will then be sble to fit more contributors.



@HarshKhandeparkar  done

**Comment by subhahu123** [comment]
> Cool! Are you working on removing the bots?

sorry what bots .....................u r refering to ......

**Comment by HarshKhandeparkar** [comment]
The bots like dependabot sre included in the contributors list. Can you remove those?

**Comment by subhahu123** [comment]
> The bots like dependabot sre included in the contributors list. Can you remove those?

i will try

**Comment by subhahu123** [comment]
> > The bots like dependabot sre included in the contributors list. Can you remove those?
> 
> i will try

got it working on it

**Comment by subhahu123** [comment]
> > > The bots like dependabot sre included in the contributors list. Can you remove those?
> > 
> > 
> > i will try
> 
> got it working on it

@HarshKhandeparkar  done
https://community-toolbox-a2v6ul.stackblitz.io
check this

**Comment by subhahu123** [comment]
> Why is this space empty? Is this a bug?
> ![Screenshot_20190319-153944__01](https://user-images.githubusercontent.com/34770591/54597888-4d299580-4a2f-11e9-9403-cba57c609eb2.jpg)

requires little more changes only ..........
