### ISSUE TITLE
package.json points to a different repo

### ISSUE THREAD

**Issue by nemesisdesign** [publiclab/community-toolbox#17]
https://github.com/publiclab/community-toolbox/blob/master/package.json

repository url points to `git+https://github.com/jywarren/community-toolbox.git`

**Comment by jywarren** [comment]
Hi, thank you! good catch! I think i just fixed this! 

Also, i'm curious -- where did you happen to find the project? Thanks!

**Comment by nemesisdesign** [comment]
On the GSoC mentors mailing list
