### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by nemesisdesign** [publiclab/community-toolbox#18]
Hi,

some install instructions would be helpful.

I tried `npm install` but I get this error:

```
npm http 404 https://registry.npmjs.org/juliangruber/tap-finished/0.0.2
npm ERR! 404 'juliangruber' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by jywarren** [comment]
hmm, thanks for the suggestion! i think we didn't anticipate installation
via npm that much ... but i can release a copy now.

You can also fork the repository on GitHub if that's helpful -- and then
create a gh-pages branch to run it from there.

**Comment by jywarren** [comment]
ok, published! hope it works...

**Comment by jywarren** [comment]
How'd that work?

**Comment by nemesisdesign** [comment]
I did not install via npm, I cloned the repo and ran `npm install`. What's the correct way of doing it?

**Comment by jywarren** [comment]
Actually this should've worked -- and you're right, that's the correct install process. I bet it has to do with:

https://github.com/publiclab/community-toolbox/blob/762b3b3fd58009b041ad0b49a7368ac4261c46ca/package.json#L36-L38

Maybe we need to update the version numbers for those lines?

**Comment by Paarmita** [comment]
@jywarren @nemesisdesign I cloned the repo and tried npm install and open index.html in the browser. It worked for me. Can I add these install instructions?
Do we need to update the versions of these?

**Comment by jywarren** [comment]
This sounds great! The versions of which, the npm modules? Thanks!

**Comment by Paarmita** [comment]
@jywarren The versions of these     
    "tap-spec": "^4.1.1",
    "tape": ">=4.7.0",
    "tape-run": "^3.0.0"
I didn't changed them.

**Comment by jywarren** [comment]
You probably don't need to change the versions but if they did get updated
when you installed, you're welcome to submit a PR with the updated
versions. It'll probably help keep our code up to date.

Thanks for your help!
