### ISSUE TITLE
If repository is not specified, get all issues w/ given label across the whole organization

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#2]
This could be developed in https://github.com/publiclab/community-toolbox/tree/master/src/community-toolbox.js

Roughly, the steps would be:

1. make a new method called `getIssuesForOrg()`, and inside: 
2. see if a repo was specified in the initial call
3. find a list of repositories for the given org, store in `var repos`
4. for each of those, run `getIssuesForRepo()`
5. on the response callback for `getIssuesForRepo()`, add the issues to the page

Any help on this would be lovely!

**Comment by jywarren** [comment]
@gr2m - hope you're well -- this whole thing (just posted this weekend) was inspired in part by your awesome Ubersicht project!!!

**Comment by gr2m** [comment]
oh Ubersicht was all @espy :)

I love https://publiclab.github.io/community-toolbox/ 👏

**Comment by jywarren** [comment]
Working on this, PublicLab has lots of repositories, so we get 30 in the first request for repos, then query each of the 30 for issues matching a label, and we've reached our hourly rate limit of 60... which is no good.

https://developer.github.com/v3/#rate-limiting

Not sure about either batching or perhaps subselecting only some of the repos... by tag maybe?

**Comment by jywarren** [comment]
Maybe we can do a batch query for issues using the search API...? https://developer.github.com/v3/search/#search-issues

**Comment by jywarren** [comment]
Yes: https://github.com/search?q=org%3Apubliclab&type=Issues&label=first-timers-only

**Comment by jywarren** [comment]
https://api.github.com/search/issues?q=org%3Apubliclab&label=first-timers-only works! It may be rate limited but i'm not sure if it falls under the search api rate limiter or the 60/hour general rate limit. But this works.

**Comment by jywarren** [comment]
Pretty sure it's not normal rate-limiting; i'm past my rate limit but can still load that query.

**Comment by jywarren** [comment]
Oops it's actually  https://api.github.com/search/issues?q=org%3Apubliclab+label%3Afirst-timers-only

Made a request here to include this upstream but we can do this here otherwise. 

https://github.com/MichielvdVelde/github-api-simple/issues/3

**Comment by jywarren** [comment]
OK, just need to add contributors for all repositories, now!

**Comment by jywarren** [comment]
https://developer.github.com/v3/search/

**Comment by jywarren** [comment]
Actually it may not be possible: https://developer.github.com/v3/search/#search-users

**Comment by jywarren** [comment]
Working here! https://jywarren.github.io/community-toolbox/#r=all
