### ISSUE TITLE
No contributors data returned with 'r' and 'o' parameters except "all" and "plots2"

### ISSUE THREAD

**Issue by nikramakrishnan** [publiclab/community-toolbox#20]
The `r` and `o` hash parameters break the contributors API except for the two cases with `r=all` and `r=plots2`

For example:

- https://publiclab.github.io/community-toolbox/#r=community-toolbox should return all contributors for `community-toolbox`, as `o` defaults to `publiclab`
- https://publiclab.github.io/community-toolbox/#o=wbsoft&r=frescobaldi should return contributors for `wbsoft/frescobaldi`

**Comment by jywarren** [comment]
Oy, good catch. This is why we need some better testing! 

Marking as `help-wanted` and perhaps we can link to the line numbers where it breaks down...

**Comment by RignonNoel** [comment]
I will create a PR on this issue, i've checked after libre planet for use this tool and i already know how to fix it.

**Comment by jywarren** [comment]
Awesome. We've wanted to expand the contributors listing and havent been
yet able to figure it out, we'd love your help! Thanks!!!!

**Comment by jywarren** [comment]
Amaze!!!

**Comment by nikramakrishnan** [comment]
Great work figuring out the problem @RignonNoel !

**Comment by nikramakrishnan** [comment]
Fixed in #23 
Closing this!

**Comment by jywarren** [comment]
oh awesome, great!
