### ISSUE TITLE
Add filter button for recent contributors' list

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#202]
Currently, there is no filter option on the recent contributors' list. There can be some options allowing the user to arrange the list according to his needs.

The filter should be based on,
- alphabetical,
- most recent contributors first.

There can be other filters also which can be implemented later...suggestions are welcome :)

**Comment by jywarren** [comment]
This is awesome and perhaps we could modify `fetchAllRecentMonthCommits()` to be generically `fetchAllCommitsForPeriod(org, repos, queryTime, start, end)`?

https://github.com/publiclab/community-toolbox/blob/30dd90769c0984144229438490260da74030d7b2/src/utils/recentContribsUtil.js#L36-L40

@gauravano was interested in being able to select the past 2 months of recent contributors in our check-ins (https://github.com/publiclab/plots2/issues/5627). This might be a relatively easy way to expand this functions use for arbitrary time periods. 

Thanks @Rishabh570 -- Community Toolbox continuing to be super useful!!!

**Comment by Rishabh570** [comment]
Yes, it can be expanded to include past X months' commits and this goes very well with the topic of this issue...I'll include it.

**Comment by Rishabh570** [comment]
So, I'm planning to do a followup refactor work after my already open PRs get merged. This will make it convenient for writing tests & making the logic of recent contributors flexible and for reading the code generally...Currently, I'm looking at the `utils/` folder as a place which needs to be refactored the most as it contains most of the logic...Here's how I think the structure would look like,

![Screenshot from 2019-06-20 21-05-01](https://user-images.githubusercontent.com/25483260/59862201-fb7f0700-939f-11e9-82c2-880325e6b0b7.png)


I guess we should get done with this refactoring work before we work on making the logic of recent contributors flexible (& most probably providing a filter for past 1, 2 and maybe 3 months).

What do you think?

**Comment by jywarren** [comment]
I think that sounds fine! The basic 1 month sounds good and you're probably
right that some more code reorganization is a good early investment!

**Comment by Rishabh570** [comment]
I've been working on the recent contributors' section's logic for the past couple days and most of the logic part is almost done. Here's a quick GIF showing the changes,

![filter](https://user-images.githubusercontent.com/25483260/61607823-14fcc280-ac6e-11e9-894a-f2336dfc6d29.gif)

The main things that are remaining on this are,
- Enhancing the UI a bit of the dropdowns list present,
- Showing the status of the `Show` option alongside so that people can easily notice the time period for which the data is shown

@publiclab/reviewers @jywarren Please take a look, is there anything more which needs to be there in this filter options bar?

@gauravano Will this resolve the problem of looking for contributors' data for previous X months, the one you were discussing in the check-in?
