### ISSUE TITLE
Remove redundant function from community-toolbox.js

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#218]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [community-toolbox.js](https://github.com/publiclab/community-toolbox/blob/main/src/scripts/community-toolbox.js) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

**CHANGES**

- In **src/scripts/community-toolbox.js**,

```diff
$DIFF
- function displayIssuesForRepo(org, repo, label, selector) {
- toolbox.api.Issues
- .getIssuesForRepo(org, repo, { qs: { labels: label } })
- .then(function onGotIssues(issues) {
- issues.forEach(function(issue) {
- toolbox.issuesUI.insertIssue(issue, selector);
- });
- });
- }
```

_After doing these changes, run `grunt build` before making a commit_

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by koslofse** [comment]
I created a pull request here
https://github.com/publiclab/community-toolbox/pull/220

**Comment by smohtadi** [comment]
Hi, I am a first-timer, and would like to work on the issue or help.

**Comment by Sjain020188** [comment]
Hello, I am first timer. I would like to work on this if its still open?

**Comment by Sjain020188** [comment]
I made PR fir this.

**Comment by Rishabh570** [comment]
So it seems like @koslofse is not working on it anymore, @Sjain020188 you can work on it...in case @smohtadi is not willing to continue with this issue!?

Sorry everybody for the inactivity here...please check out https://code.publiclab.org/#r=all for more `first-timer-only` issues.

**Comment by smohtadi** [comment]
Hi, I'm working on another project right now, so @Sjain020188 you can word on it if you want.

**Comment by Sjain020188** [comment]
I already made PR for this.

**Comment by mastal88** [comment]
Hi,
I will prepare PR for this.

**Comment by nmeurer** [comment]
No one seems to be working on this right now.
I'll try my best as a first-timer!

**Comment by anushtha1011** [comment]
hi i am first timer and would like to make a PR for this

**Comment by joshuiaclan** [comment]
Hi! I am a first timer and I would like to help you on your project :)

**Comment by sahajkedia** [comment]
Hi there, I would like to make a pull request for this.

**Comment by jywarren** [comment]
Hi all, my apologies for not seeing peoples' inquiries. We would love help with this so if you would like to, please just begin by saying "i'd like to work on this" and then you can go ahead and open a pull request and link to it from here! Thank you very much!

**Comment by akanksha-v** [comment]
@jywarren I think this issue has been resolved as the above-mentioned function cannot be located inside src/scripts/community-toolbox.js. Please look into this!

**Comment by jywarren** [comment]
Thank you!!! Much appreciated.
