### ISSUE TITLE
Enable default welcome page text to source from .json file via URL hash

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#22]
We have some nice text in our example welcome page (which we use for Public Lab projects) -- 

https://publiclab.github.io/community-toolbox/#r=all

But if people want to begin using that just by adding URL hashes for another organization and repository (as in the README), they still see PL text. Let's make it possible to have a .json file that supplies text so people can get this running quickly for themselves!

**Comment by RignonNoel** [comment]
I'm really interesting by this issue so i will not have to manage a fork and lost all your upgrade  :sparkles:

If you need some help i'm available to do it if you already have a list of option you want to made available.

**Comment by angelfeliz** [comment]
Hello, It look like I can jump in to this issue, can I worke it?

**Comment by jywarren** [comment]
That'd be terrific, thanks!

On Jul 3, 2018 8:10 PM, "Angel Eduardo" <notifications@github.com> wrote:

Hello, It look like I can jump in to this issue, can I worke it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/community-toolbox/issues/22#issuecomment-402325635>,
or mute the thread

**Comment by gauravano** [comment]
Hi @RignonNoel @angelfeliz just checking if any of you are interested in solving or breaking this issue further. Thanks!

**Comment by RignonNoel** [comment]
I had time in March after i heard about this project during LibrePlanete, but since this project is not really active i developed my own intern tool in place and i don't have time to help on this. Sorry,

**Comment by gauravano** [comment]
Hi RignonNoel, no problem. Hopefully, we could work on some other idea or project someday. 

Thanks!
