### ISSUE TITLE
Bug in Recent Contributors list

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#222]
Hi! I was on the page today https://code.publiclab.org/#r=all and noticed `Recent Contributors` was blank, with an error on what I think is this line, in `fetchAllRecentMonthCommits`:

https://github.com/publiclab/community-toolbox/blob/30dd90769c0984144229438490260da74030d7b2/src/utils/recentContribsUtil.js#L57

The error is:

```
Uncaught (in promise) TypeError: Cannot read property 'login' of null
    at mappingToCommits (community-toolbox.js:82273)
    at Array.map (<anonymous>)
    at gotResponseJson (community-toolbox.js:82271)
    at async Promise.all (/index 5)
```

It looks like we're not running the latest, as the error on gh-pages shows this code:

```js
                .then(function gotResponseJson(response) {
                    if(response!=null) {
                        let partialResult = [];
                        response.map(function mappingToCommits(commit, i) {
                            if(commit!=null) {
                                if(!commitersSet.has(commit.author.login)) { // this line causes the error
                                    commitersSet.add(commit.author.login);
                                    partialResult.push(commit);
                                    results.push(commit);
                                }
                            }
                            return true;
                        });
```

Just trying to document well! Maybe this is fixed in the latest code and we need to publish? Thanks!

**Comment by jywarren** [comment]
could be related to #202 ?

**Comment by Rishabh570** [comment]
@jywarren Yes, this bug is fixed in the latest version...I'm pushing the latest one to `gh-pages`.

**Comment by Rishabh570** [comment]
@jywarren I'm not able to get the site running again, please help...

**Comment by jywarren** [comment]
No prob! let me take a look.

**Comment by jywarren** [comment]
Thanks for already having fixed this! :-)

OK, so you have to preserve the existing gh-pages branch, you can't force push to it, because it has to include the `node_modules` folder as well (since it needs some of the dependencies to run). So I merge commit to gh-pages; my process is:

```

git checkout main
git pull publiclab main
git checkout gh-pages
git merge main -m 'merge from main'
npm install # in case there are any new npm modules needed
git add -f node_modules
git commit -m 'new node modules'
git push publiclab gh-pages
git checkout main
npm install
```

**Comment by jywarren** [comment]
Up again with latest! https://code.publiclab.org/#r=all

**Comment by Rishabh570** [comment]
Ooh, so I accidentally removed `node_modules` I guess...thanks for clarifying the steps required :+1:
