### ISSUE TITLE
inverted image colors.

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/community-toolbox#233]
### Please describe the problem (or idea)
Switching night mode inverts the images. Is thie supposed to happen?
![Screenshot_20190707-115716](https://user-images.githubusercontent.com/34770591/60764853-7e7ead80-a080-11e9-84cd-e9f035616a38.jpg)

Secondly, when I toggle the show monthly button here, it turns the image greyscale from inverted.

![Screenshot_20190707-115735](https://user-images.githubusercontent.com/34770591/60764859-aa9a2e80-a080-11e9-88ba-0f67976f7e99.jpg)

### Browser, version, and operating system
Firefox mobile version: latest (idk the number)
Android 9

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Rishabh570** [comment]
Images are supposed to be turned into grayscale, does this happen when you toggle the button to _night_ or when you visit the page with night theme already on?

**Comment by HarshKhandeparkar** [comment]
I toggled it and this happened.

**Comment by Rishabh570** [comment]
Okay, it seems like either CSS grayscale filter is not coming into play or images are hanging in the loading state while you click the toggle (so querySelector didn't catch them) :thinking:

Thanks for reporting the issue :+1:

**Comment by Rishabh570** [comment]
This issue has a high frequency of occurrence, I'll take a look at what's possible.

**Comment by vaibhavmatta** [comment]
Is anyone working on this issue? @Rishabh570

**Comment by Rishabh570** [comment]
As of now, nobody is working on it. You can go ahead!

Thanks!

**Comment by vaibhavmatta** [comment]
I am working on it now.!

**Comment by akanksha-v** [comment]
@HarshKhandeparkar I believe this issue has been resolved as of now black and white images are displayed in night mode.

![night-mode](https://user-images.githubusercontent.com/59011370/102645717-eb103e00-4188-11eb-9f68-d771b3171614.png)

**Comment by HarshKhandeparkar** [comment]
yaay!

![pika-wow](https://cdn.discordapp.com/emojis/754416439812816953.png?v=1)

**Comment by akanksha-v** [comment]
Now we can close this issue @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
I am not a maintainer here so Idk but it looks fine to me :)

**Comment by govindgoel** [comment]
Closing this as it is fixed.
