### ISSUE TITLE
Add copy to clipboard button for recent contributors list

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#240]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html), [copyToClipboard.js](https://github.com/publiclab/community-toolbox/blob/main/examples/copyToClipboard.js) and [demo.css](https://github.com/publiclab/community-toolbox/blob/main/examples/demo.css) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

**FILES TO CHANGE:**

- **index.html**,

```diff
$DIFF
- Remove everything from line 187 to 198.

+ <div class="recent-contribs">
+ <div title="copy to clipboard" class="copybutton"><i class="fa fa-clipboard" aria hidden="true"></i></div>
+ <p style="display: inline;">Below are the list of active contributors <p id="recency-label" style="display: inline;">last week: </p> <a href="#" class="nightmode-adapt"id="toggle-contributors">(Show monthly)</a></p>  
+ <div class="well recent-contributors"><p class="usernames"></p><hr /><p class="avatars"></p></div>
+ </div>
+ <h2 class="contributors-head">Contributors</h2> 
+ <div class="contribs">
+ <div title="copy to clipboard" class="copybutton"><i class="fa fa-clipboard" aria-hidden="true"></i></div>     
+ <p>This project was made possible by many contributors, including the following GitHub users:</p>      
+ <div class="well contributors"><div id="spinner-icon" style="text-align: center;"><i class="fa fa-spinner fa-spin"></i></div><p id="contrib-names" class="usernames"></p><hr /><p class="avatars text-center"></p></div>
+ </div>
```

- **copyToClipboard.js**

```diff
$DIFF
- Remove everything from line 2 to line 17.

+ let copyButton = $(".copybutton");
+ let body = document.querySelector('body');
+ let dummyInp = document.createElement("input");
+ let usernames;
+ copyButton.map(function(item, ele) {
+ ele.addEventListener("click", function(event) {
+ event.preventDefault();
+ usernames = $(this).parent().children(this.lastChild).find(".usernames")[0];
+ let names = usernames.textContent;
+ dummyInp.setAttribute('type', 'text');
+ dummyInp.setAttribute('value', `${names}`);
+ body.appendChild(dummyInp);
+ dummyInp.select();
+ document.execCommand("copy");
+ dummyInp.setAttribute('type', 'hidden');
+ })
+ })
```

- **demo.css**

```diff
$DIFF
- #copybutton {
+ .copybutton {

- #copybutton i {
+ .copybutton i {

- #copybutton:hover {
+ .copybutton:hover {

- #copybutton:active {
+ .copybutton:active {
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Rishabh570** [comment]
The copy to clipboard button should be visible next to the `Recent Contributors` section on the landing page (index.html). Clicking that should copy the usernames written just below it.
Please take these things into consideration when submitting a Pull Request.

![Screenshot from 2019-07-29 13-13-15](https://user-images.githubusercontent.com/25483260/62030476-c8336180-b202-11e9-8d3d-233d46dc25df.png)

**Comment by AProperName** [comment]
Hello. I'm here to claim this issue. Thanks.
