### ISSUE TITLE
Remove explanatory line and design changes

### ISSUE THREAD

**Issue by gauravano** [publiclab/community-toolbox#254]
<img width="1175" alt="Screenshot 2019-08-19 at 11 32 13 PM" src="https://user-images.githubusercontent.com/20878070/63288533-8dd95380-c2da-11e9-89d7-dfb6548970d4.png">

The footer to connect via social media has an explanatory line that says **You can connect with us on any of these platforms:**. I think we can remove this line as it's intuitive and so the line is not required.

**Design changes:**
1. Centre align the line Page powered by 
2. Try to see how social media icons after reducing the padding will look

**Comment by pydevsg** [comment]
@gauravano , I would like to work on this issue. Can you assign this to me,please?

**Comment by Rishabh570** [comment]
Sure @pydevsg, go ahead! :)

**Comment by pydevsg** [comment]
After doing the mentioned above , the page looks like this @gauravano 

![public_lab_navbar_change](https://user-images.githubusercontent.com/40278255/63317622-2bf80880-c331-11e9-92ec-16f8cba1c8c7.png)

Is it fine?

**Comment by pydevsg** [comment]
I have changed this page as mentioned above, @gauravano 

![PL_CommunityPage_footer_change](https://user-images.githubusercontent.com/40278255/63320480-8ac27f80-c33b-11e9-8f96-d590d07d5b4e.png)

Is it fine?

**Comment by gauravano** [comment]
How about reducing space b/w the social media icons?

**Comment by pydevsg** [comment]
@gauravano I did the same in console and removing space in big screens isn't looking much good.
In the mobile view , there were two lines for the social media icon, I made the change to reuce them to one line.

**Comment by pydevsg** [comment]
@Rishabh570 , can you please review this?

**Comment by Rishabh570** [comment]
@pydevsg You can reduce the space for mid/standard laptop screens and then increase it a bit in case of larger screens...that would work I guess. What do you think?
Reducing the gap between icons in small screens is perfectly fine...

**Comment by pydevsg** [comment]
@Rishabh570 , thanks for the review. 
I checked the same in google chrome toolbar and saw that there ain't much change if I do so.
It looks good in every screen :)

**Comment by Rishabh570** [comment]
Can you share a GIF showing icons for different widths, it helps in the assessment.

Thanks!

**Comment by pydevsg** [comment]
@Rishabh570 I will surely send the screenshots in place of gif for different views of the website very soon. :)

**Comment by pydevsg** [comment]
@gauravano , my pull request is merged can you check it https://github.com/publiclab/community-toolbox/pull/255  and can add the feature in the main website, it is still not featuring it , thanks

**Comment by gauravano** [comment]
Yup, great work. Your change will be released soon into production. Thanks!

cc @jywarren
