### ISSUE TITLE
Add a "hall of fame" issues list at the bottom of the page

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#261]
A list of issues that are labeled as `hall-of-fame` issues should be displayed at the bottom of the page just above "connect with us" section. When there are no `hall of fame` issues, the list should not be occupying any space other than the heading. It should be just like stale issues list with overflow set to auto.

![Screenshot from 2019-08-29 14-01-17](https://user-images.githubusercontent.com/25483260/63924215-84cc4d00-ca65-11e9-9841-12a495a4e915.png)

It should look something like this.

**Comment by jywarren** [comment]
Love this!

**Comment by pydevsg** [comment]
I would love to take this issue @Rishabh570 , Can you please assign this?

**Comment by vivianedias** [comment]
If this issue is still open I'm up for it :smile:

**Comment by jywarren** [comment]
Hello! It's not necessary to assign it, and we're happy to have help from
folks! Sudipto if you're still interested please go ahead, if not, Viviane
we'd love your help! Thanks!

**Comment by ekamwalia** [comment]
Hey @vivianedias, are you working on this issue? If not, I would love to contribute!

**Comment by vivianedias** [comment]
Yes, I am @ekamwalia :)

**Comment by olarotseyi** [comment]
Hi @vivianedias Are you still working on this issue?

**Comment by Rishabh570** [comment]
Hi all :raised_hand_with_fingers_splayed:,
@vivianedias if you're not working on this, others can consider taking this up. Or, If you're stuck, please feel free to reach out/comment here :+1: 

Thanks!

**Comment by DevanshCodes** [comment]
I want to take this issue! Can I work on this?

**Comment by YogeshSharma01** [comment]
Hi, @jywarren and @Rishabh570 @DevanshCodes  anyone working on this?

**Comment by jywarren** [comment]
Hi all, i think we'd love help with it @YogeshSharma01 - thanks!

**Comment by YogeshSharma01** [comment]
Hi @jywarren and @Rishabh570  I am a bit confused about what all issues should be added in the Hall of Fame section. If you can elaborate a little on it; that would be a big help.
And like do we only fetch the issues of community-toolbox or all the public lab repos issue?

**Comment by jywarren** [comment]
Hi @YogeshSharma01 i'm going to merge this into #257 as there's more info there. Thank you!!!!
