### ISSUE TITLE
Environment setup on Vagrant produces 403 errors - contributors list not loading

### ISSUE THREAD

**Issue by ReardGjoni** [publiclab/community-toolbox#269]
On a simple Vagrant machine, trying to set up the repo - the contributors list can't get loaded, 403 forbidden.

This is what my Vagrantfile looks like:

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  for i in 8000..8080
    config.vm.network "forwarded_port", guest: i, host: i
  end

  config.vm.network :private_network, ip: "10.10.10.61"

  config.vm.synced_folder "../www", "/var/www"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install 10
  SHELL
end
```

## Errors on console:

![Console Errors](https://user-images.githubusercontent.com/35934418/65792596-6345aa80-e164-11e9-9c78-698580af9abb.PNG)

### Browser, version, and operating system

Complete setup includes:

Host: Windows 10 Home Edition,
Guest: Ubuntu
Browser: Chrome, also tested on Brave(chromium-based)

Seems to be the same as [https://github.com/publiclab/community-toolbox/issues/112](url)

Any specifications on running the application on a virtual machine?!

Thank you

**Comment by Rishabh570** [comment]
Hi @ReardGjoni, so 403 is because of the API's rate limit of 60 requests/hr...If it exceeds that, you get the error (you need to wait for it to get refreshed if app cache is empty).
Secondly, running on development would be better with `npm start` because some features are supported on that only.
