### ISSUE TITLE
'r=all' not working for embedded issues link

### ISSUE THREAD

**Issue by BaaniLeen** [publiclab/community-toolbox#28]
Unable to fetch the issues relevant to all the repos using 'r=all'.

Eg: `<iframe src="https://publiclab.github.io/community-toolbox/examples/embed.html#o=publiclab&r=all"
      style="border:none;" width="100%" height="600px"></iframe>`

This shows up as the error:
![screen shot 2018-07-26 at 6 30 52 pm](https://user-images.githubusercontent.com/22029744/43263849-133f5eea-9102-11e8-85ed-bdad888d7291.png)

If someone could help fix this issue, it would be really helpful. Thanks! :)

**Comment by Paarmita** [comment]
@BaaniLeen Can u elaborate the issue more, that where u want to use iframe and r=all?

**Comment by Rishabh570** [comment]
I would like to work on this.
