### ISSUE TITLE
Stale issues doesn't repoint at other respositories

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#282]
When visiting https://code.publiclab.org/#r=mapknitter (using the project selector dropdown), the stale issues listing doesn't seem to load from `mapknitter` but instead the default `plots2`. We should rewire it to point at the appropriate repository. 

We'd love help with this one!

**Comment by Rishabh570** [comment]
Yeah, so as of now, the stale issues' list fetches issues for all the org at once and then filters accordingly...to make it custom so that it can show appropriate data for a particular repository, we need to fetch & store stale issues separately for each and every repository that user visits.
For that, we can fetch issues for the whole org at once and then save it in separate buckets based on the repository it belongs to. Currently, we save all the stale issues as a single object in the storage. (see [here](https://github.com/publiclab/community-toolbox/blob/main/src/utils/staleIssuesUtil.js#L53))

**Comment by Tanish0019** [comment]
@jywarren can I work on this?

**Comment by Rishabh570** [comment]
Yes, sure @Tanish0019...you can go ahead. Currently, all the stale issues fetched are stored in a single object for all of the repositories (you can see [here](https://github.com/publiclab/community-toolbox/blob/main/src/utils/staleIssuesUtil.js#L53)).

The workflow for storing data for a particular repository follows a certain code style. `Keys` in the database are named after the repo it contains the data of. [ you can see how contributors' data is stored for every single repo [here](https://github.com/publiclab/community-toolbox/blob/main/src/utils/contribsUtil/fetchRepoContribs.js#L20) ].

Feel free to ping me for any queries!
Thanks.

**Comment by DevanshCodes** [comment]
Hey, if its still open, can I work on this?

**Comment by DevanshCodes** [comment]
> Yes, sure @Tanish0019...you can go ahead. Currently, all the stale issues fetched are stored in a single object for all of the repositories (you can see [here](https://github.com/publiclab/community-toolbox/blob/main/src/utils/staleIssuesUtil.js#L53)).
> 
> The workflow for storing data for a particular repository follows a certain code style. `Keys` in the database are named after the repo it contains the data of. [ you can see how contributors' data is stored for every single repo [here](https://github.com/publiclab/community-toolbox/blob/main/src/utils/contribsUtil/fetchRepoContribs.js#L20) ].
> 
> Feel free to ping me for any queries!
> Thanks.

Where can I pm you?

**Comment by DevanshCodes** [comment]
Hey @jywarren @Rishabh570 Can you please review the PR? I saved the stale issues belonging to different repos in different buckets, based on the repo name.

**Comment by jywarren** [comment]
Hi, I'm sorry, can you link us to the PR? I don't see which you're working on. Thank you!!

**Comment by DevanshCodes** [comment]
> Hi, I'm sorry, can you link us to the PR? I don't see which you're working on. Thank you!!

Hey, here is the PR: https://github.com/publiclab/community-toolbox/pull/306

Thanks!

**Comment by DevanshCodes** [comment]
Hey, Sorry for the Delay I opened a new PR, I was having trouble committing on the old PR, the new PR is here: https://github.com/publiclab/community-toolbox/pull/314 , Can you please review it, I have written all the tests and the tests are running fine as they should.
