### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by somenath1435** [publiclab/community-toolbox#299]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Please check PR for images regarding UI issue

### Browser, version, and operating system
OS: Ubuntu 16
Browser: Google Chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Rishabh570** [comment]
@somenath1435 Thanks for reporting the issue. :+1:

**Comment by somenath1435** [comment]
@Rishabh570 you are welcome. Can you suggest how can I contact you?(FB/whatsapp/insta)
