### ISSUE TITLE
Select repository button does not contain anything!

### ISSUE THREAD

**Issue by aashimgarg** [publiclab/community-toolbox#316]
While clicking on the select repository button it does not select anything as it does not contain anything.

**Comment by DevanshCodes** [comment]
> While clicking on the select repository button it does not select anything as it does not contain anything.

Select repository button is working on the website and the data except stale issues are changing i.e. contributors, recent contributors. Stale issues is not working because stale issues were not grouped according to the Repositories.

**Comment by govindgoel** [comment]
Since the issue has been fixed and things are working fine so it can be closed.If you still face the issues try fetching the changes and rebasing it.
