### ISSUE TITLE
Stale issues list is not displaying anything

### ISSUE THREAD

**Issue by aashimgarg** [publiclab/community-toolbox#318]
Stale issues list does not contain anything. It is just showing an empty list.

**Comment by Rishabh570** [comment]
@aashimgarg Can you please attach the snapshot of the error from the developer console, would be a huge help in tracking down the issue.

Thanks!!!

**Comment by aashimgarg** [comment]
![Screenshot from 2020-01-21 00-52-21](https://user-images.githubusercontent.com/55639487/72752490-4f78f500-3be8-11ea-9e52-4fb66f33ba8a.png)

**Comment by govindgoel** [comment]
@aashimgarg As the issue has been fixed so it can be closed I guess.

**Comment by akanksha-v** [comment]
@aashimgarg @jywarren we can close this issue!

**Comment by govindgoel** [comment]
Closing it as it has been fixed!
