### ISSUE TITLE
Not displaying repo,stale issues when running on local system

### ISSUE THREAD

**Issue by govindgoel** [publiclab/community-toolbox#326]
### Please describe the problem (or idea)
When trying to run the toolbox on the system getting every field as empty
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
It should list the repos.

### Please show us where to look

https://code.publiclab.org/ 

I
![ ](https://media.giphy.com/media/dunwzCH5kYTd8M3pfj/giphy.gif )

### Browser, version, and operating system
Brave Browser Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Firefox Browser Version 71.0 (64-bit)

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by govindgoel** [comment]
@Rishabh570  Please tell me what to do??

**Comment by cesswairimu** [comment]
Hi @Rishabh570 , do you mean the stale issues, fto authors and such?

**Comment by DevanshCodes** [comment]
> @Rishabh570 Please tell me what to do??

Can send the screenshot of the error which is logging in the console?

**Comment by govindgoel** [comment]
@DevanshCodes  I have included the GIF of the issue I am facing at least it should fetch the repositories

**Comment by govindgoel** [comment]
Solved!
