### ISSUE TITLE
Fork me on github ribbon abruptly moving

### ISSUE THREAD

**Issue by govindgoel** [publiclab/community-toolbox#328]
### Please describe the problem (or idea)
Fork me on github  abruptly moving when changing the repository from dropdown.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
The tag should not move.

### Please show us where to look

https://code.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
Brave Browser Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Firefox Version 71.0 (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

![ ](https://media.giphy.com/media/f5eXrlhr7AhiacUBlz/giphy.gif)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by govindgoel** [comment]
I will try to work on this.

**Comment by govindgoel** [comment]
@Rishabh570  Please look into this

**Comment by Rishabh570** [comment]
@govindgoel Go ahead and open up a PR for this. Thanks :+1:
