### ISSUE TITLE
Website requires too much scrolling

### ISSUE THREAD

**Issue by DevanshCodes** [publiclab/community-toolbox#330]
Currently the community-toolbox requires a lot of scrolling for the user to do, while reaching the bottom of the page. Navigation is also not much clear. Like the UX of the website can be made better. 

Scrolling can be reduced if we fix the height of each containers like 'first timers only issues' and then add  scrolling in them, thereby reducing the overall website length.

![pub123](https://user-images.githubusercontent.com/48180687/73606852-d9f02a00-45d4-11ea-9be6-d9cd0cc6b795.gif)

For improving the navigation for the website, we can add `sticky navigation-bar`to the left (empty space), through which user can easily navigate through website.

https://code.publiclab.org/

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Great. Go for it

**Comment by DevanshCodes** [comment]
Cool! I am working on it.  :)

**Comment by DevanshCodes** [comment]
Here's the PR: https://github.com/publiclab/community-toolbox/pull/336, @SidharthBansal @Rishabh570 . :)
