### ISSUE TITLE
Align the text the centre in footer

### ISSUE THREAD

**Issue by govindgoel** [publiclab/community-toolbox#334]
### Please describe the problem (or idea)

Align the text in footer(Page powered by... ) in centre 

![fix](https://user-images.githubusercontent.com/52847415/74088105-a9b6f880-4ab8-11ea-9226-db73594cc9bb.png)

### Please show us where to look

https://code.publiclab.org/

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by DevanshCodes** [comment]
You can try forking the main branch, issue has been fixed and is not there.

**Comment by govindgoel** [comment]
@DevanshCodes  Did that but not showing in my localhost server
