### ISSUE TITLE
Changing the repository from dropdown  in night mode leads back to day mode 

### ISSUE THREAD

**Issue by govindgoel** [publiclab/community-toolbox#341]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Issue with the night mode

> What did you expect to see that you didn't?
Changing the repository in night mode leads back to day mode and then after a while changes back to night mode

### Please show us where to look

https://code.publiclab.org/ ...

![ ](https://media.giphy.com/media/UsGR94c3wXBM3Uvgc0/giphy.gif)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by joshuiaclan** [comment]
Hi Can I work on this?

**Comment by akanksha-v** [comment]
@govindgoel Is this issue resolved?
As I feel now website changes perfectly from dark to light mode and vice versa.

**Comment by govindgoel** [comment]
Yeah its resolved
