### ISSUE TITLE
Weekly Community Check-In #72 - Outreachy Wrap up

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/community-toolbox#386]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Wrap up 

This week being the last formal week of Outreachy, lets share some good interactions we have had we the Outreachy interns and also feel free to mention some of their work you have loved and appreciate them.  I know  @shreyaa-sharmaa , @Shulammite-Aso and @Tlazypanda will still be around wrapping up their projects and also preparing for the presentation on open call next month...so excited about this btw :smile: Happy to have you stay after that too :heart: 

If you are blocked on anything feel free to express here so that folks can help.

## To all interns:  highlighting this from @ebarry on last week's check-in

> Hi all, I'm looking ahead at the Public Lab Open Hour in September where each and every Outreachy and Google Summer of Code participant -- @Shulammite-Aso @shreyaa-sharmaa @Tlazypanda @NitinBhasneria @keshav234156 @keshavsethi @alaxalves -- will share 5 minutes about their summer's work!
> 
> * Based on input from last week's check-in, we are planning to use Zoom, and set up a meeting for at 8AM Pacific US West Coast /  8:30pm India Standard Time -- see https://everytimezone.com/?t=5f557800,384
> * Also based on input from last week's check-in, we will not meet on Tuesday September 8, but instead look at Wednesday September 9 or Monday September 14.
> 
> **Does these dates and times work for you?**
> 
> To practice, and also in case of any bandwidth problems, consider recording a screencapture of your presentation ahead of time.
> 
> Please let me know how this would work for you, i need to lock this in in the next day. Thank you!

## Thank you note to focus issues contributors

 A big big thank you to @NitinBhasneria   for working on last week's focus issue publiclab/PublicLab.Editor#591🥇🥇🥇.

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by ebarry** [comment]
Thanks @cesswairimu ! Let's book Summer of Code presentations for Wednesday September 9 at at 8:30pm India Standard Time / 8AM Pacific US West Coast -- see https://everytimezone.com/?t=5f557800,384 for more time zones.

**Comment by Tlazypanda** [comment]
Hey everyone! :wave: I am still wrapping my head around that we are actually at the end of our internships these 3 months have passed so fast realization kicking in xD

Thanks to all the mentors,community members and everyone for this amazing experience and always helping us push beyond boundaries and challenging us with new and exciting things :fire: @jywarren @cesswairimu @icarito  @ebarry @sagarpreet-chadha @SidharthBansal @VladimirMikulic and to all the fellow interns for all the peer reviews and general help in certain modules of code :heart: 

This week I worked on the print preview thing  https://github.com/publiclab/plots2/pull/8292 and also opened some ftos and performance prs(https://github.com/publiclab/plots2/pull/8306). In the coming weeks plan to do some more performance optimisations, alternative text for images, adding some more points to the documentation and opening up ftos :sweat_smile: Also some of my previous prs (https://github.com/publiclab/plots2/pull/7996 https://github.com/publiclab/plots2/pull/7958 https://github.com/publiclab/plots2/pull/7945 https://github.com/publiclab/plots2/pull/8159) are pending to be merged if we can get those done then I can again check the performance improvement and update on https://github.com/publiclab/plots2/pull/8292

**Comment by VladimirMikulic** [comment]
@Tlazypanda, @shreyaa-sharmaa, @Shulammite-Aso, @NitinBhasneria, @keshavsethi you all did an amazing job during these 3 months. It's really nice to see the results of your hard work. I truly wish you the best in your future career and your future endeavours! Also, big congratulations to the fellow mentors/reviewers :)

**Comment by cesswairimu** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Tlazypanda,

**Comment by jywarren** [comment]
Hello all, and a mighty congratulations to you all! 

I'm going to be going through as many steps as possible today to merge and publish your latest work. I'm extraordinarily proud of what we've been able to do together this summer. Great work, thank you to our Outreachy team as well as our mentors and everyone who pitched in! 🎉 🎉 🔥 🔥 🔥

**Comment by sagarpreet-chadha** [comment]
Hi all,
Huge shoutout to @jywarren for reviewing and merging all the PR's today, he is really a 10x programmer 💯 

Also @shreyaa-sharmaa , @Shulammite-Aso and @Tlazypanda great work on your respective projects 🎉
I enjoyed working with you all 😄  
Very excited to see your presentations in next month's open call (as mentioned by @ebarry ).

@publiclab/editor team congrats on releasing another major version 🎉

**Comment by sagarpreet-chadha** [comment]
Also are there any PR's up for review? You can tag me to your PR's if you want an in-depth review 😄 

cc @publiclab/editor

**Comment by keshavsethi** [comment]
Hey everyone 👋🏻 
I have made documentation of spam2 🚀  where I mentioned all the features in detail. https://publiclab.org/notes/keshav_sethi0004/08-18-2020/spam-management-dashboard-documentation 
@ebarry @jywarren @cesswairimu @VladimirMikulic @pydevsg and others please review and give suggestions. 🙏🏻 
Last week I worked on the insight section of spam2 https://github.com/publiclab/plots2/pull/8289. Next week I will work on tests of spam2, making some fto and fixing bugs in spam2.

Thank you, everyone ❤️ for your continuous support and suggestions 🎉

**Comment by Tlazypanda** [comment]
Hey @keshavsethi the docs look great!! The design is beautiful and you have laid out info on all the features too :tada:

**Comment by cesswairimu** [comment]
Thanks @Tlazypanda  for constantly brain storming with me new check-ins, and opening numerous check-ins throughout the summer. The work you have done to optimize the system and you are still doing is amazing and for opening so many ftos  :tada: Fantastic job the editor team huge releases, You solved a lot of bugs :tada:  :tada:  and and also really love your work integration testing :tada:  @Shulammite-Aso for opening numerous ftos :tada:  Congrats to you all Outreachy interns :tada: :tada: 

@keshavsethi awesome documentation :tada: 
Also thanks @avats-dev a new contributor who is helping first-timer get started :heart:

**Comment by cesswairimu** [comment]
Anyone willing to open next week's check-in?

**Comment by Shulammite-Aso** [comment]
> Anyone willing to open next week's check-in?

Let me do this @cesswairimu 😃

**Comment by cesswairimu** [comment]
Fantastic @Shulammite-Aso 🎉🎉 Thanks

**Comment by Shulammite-Aso** [comment]
Hi @cesswairimu here is the new check-in https://github.com/publiclab/spectral-workbench/issues/541 , please add the label and everybody 😄

**Comment by cesswairimu** [comment]
Will do thanks @Shulammite-Aso,

Moved to  publiclab/spectral-workbench#541. Thanks everyone
