### ISSUE TITLE
Add hover to show name in the avatar 

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/community-toolbox#39]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$community-toolbox.js](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js) in the `$community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
-Line 85,107,124
- return '<img width="100px" src="' + c.avatar_url + '">';
+Line 85,107,124
+ return `<a href="#" title="${c.login}"><img width="100px" src="${c.avatar_url}"></a>`;

-Line 159,174
- return '<a href="https://github.com/' + org + '/'+ repo +'/commits?author='+ c.login + '"><img width="100px" src="' + c.avatar_url + '"></a>';
+Line 159,174
+ return `<a title="${c.login}" href="https://github.com/${org}/${repo}/commits?author=${c.login}"><img width="100px" src="${c.avatar_url}"></a>`;
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by singhshubham98** [comment]
I want to work on this!!

**Comment by gauravano** [comment]
Hi @singhshubham98, @DakshGondaliya this issue is reserved for GCI. Please take a look at https://code.publiclab.org for more issues. Thanks!

**Comment by SidharthBansal** [comment]
I want to publish this but it is missing the code links, issue statement and potential solution. 
@publiclab/mentors you please edit this issue and notify me so that I can publish it.
Thanks

**Comment by Rishabh570** [comment]
@SidharthBansal I can't seem to edit the issue body, how to do it?

**Comment by sk9331657** [comment]
@SidharthBansal  We can only assign ourself mentors to the task but cannot edit it.

**Comment by SidharthBansal** [comment]
@igniteeng000 please edit it asap

**Comment by Rishabh570** [comment]
@igniteeng000 A possible solution would be,
 
In [community-toolbox.js](), on lines 85, 107 and 124
```
DIFF
- return '<img width="100px" src="' + c.avatar_url + '">';
+ return `<a href="#" title="${c.login}"><img width="100px" src="${c.avatar_url}"></a>`;
```

and on lines 159 and 174
```
DIFF
- return '<a href="https://github.com/' + org + '/'+ repo +'/commits?author='+ c.login + '"><img width="100px" src="' + c.avatar_url + '"></a>';

+ return `<a title="${c.login}" href="https://github.com/${org}/${repo}/commits?author=${c.login}"><img width="100px" src="${c.avatar_url}"></a>`;
```

**Comment by SidharthBansal** [comment]
Published onto GCI dashboard
Thanks all

**Comment by igniteeng000** [comment]
> @igniteeng000 please edit it asap

updated with the possible solution. Thanks, @Rishabh570 for suggesting the solution.
