### ISSUE TITLE
Add Public Lab dependency chart in community toolbox

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/community-toolbox#395]
### Please describe the problem (or idea)

This issue is a continuation of https://github.com/publiclab/plots2/issues/4880 where the Dependency chart is created by @jywarren. Here is a comment. highlighting the chart - https://github.com/publiclab/plots2/issues/4880#issuecomment-495932257 

## What you can do?

Coordinate with reviewers and place the image at an appropriate place in https://code.publiclab.org/ and in README of community toolbox. 

Apart from the image, the link about the software roadmap - https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome can also be added. 

I believe final image is at https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome#c26086 -- @jywarren please confirm that.

Thanks!

**Comment by gauravano** [comment]
Reviewers: @ebarry @cesswairimu @jywarren @sagarpreet-chadha

**Comment by ebarry** [comment]
Yes this looks perfect, pending @jywarren 's confirmation of this diagram being current. 🌈

**Comment by jywarren** [comment]
Yep, thanks!!

**Comment by Suiiyush** [comment]
can I work on this issue if it's up for grabs

**Comment by pydevsg** [comment]
@Suiiyush go ahead 😃

**Comment by Suiiyush** [comment]
@sagarpreet-chadha  @jywarren  @cesswairimu  @ebarry        I checked the website where the image needs to be placed and I think it should be placed above the "first-timers-only issues" section, however if there's a more suitable location then please point me to it.

**Comment by YogeshSharma01** [comment]
Hi, @Suiiyush You still working on this?

**Comment by Suiiyush** [comment]
@YogeshSharma01 Hey, no I have had no response from the mentors so Iam not working on it.

**Comment by YogeshSharma01** [comment]
Ok, @Suiiyush I'll ask about this on slack thanks.

**Comment by YogeshSharma01** [comment]
Hi, @jywarren, @ebarry, @sagarpreet-chadha, and @cesswairimu I think the image needs to be placed just above the Learn our process section. here is the sample Video, please review.

https://user-images.githubusercontent.com/51679200/106393573-e7293a00-641d-11eb-8918-91b7c0a34b77.mov

**Comment by jywarren** [comment]
Hi! I like this! Perhaps we could use simply `border-radius: 8px` CSS for the rounded corners effect? 

Also, I think this may best go at the bottom of the page, so as not to push down other critical content. What do you think?

**Comment by YogeshSharma01** [comment]
hi, @jywarren  border-radius: 8px is fine. Ok I'll set it at the bottom but it tells about the Public Lab code ecosystem, and under the photo, I'll add some text related to this cause at the bottom it would look faded and here it bends with Learn our process in the web page. What do you think, should I set it at the bottom of the page or here only?

**Comment by YogeshSharma01** [comment]
Hi, @jywarren please review PR https://github.com/publiclab/community-toolbox/pull/424
![eco-code](https://user-images.githubusercontent.com/51679200/106790114-1ab3d080-6679-11eb-8a57-87eccb25d0bb.png)

**Comment by RuthNjeri** [comment]
Done in #424
