### ISSUE TITLE
Request for joining the Organization

### ISSUE THREAD

**Issue by riturajjain2000** [publiclab/community-toolbox#417]
Hello, my name is Rituraj. I am from India.
I Would like to join this organization.
I love to contribute to open source and will love to contribute to this organization.
Please add me to your organization.

**Comment by govindgoel** [comment]
Kindly introduce yourself here https://gitter.im/publiclab/publiclab
And do check out code.publiclab.org
Kindly close the issue :)

**Comment by riturajjain2000** [comment]
> Kindly introduce yourself here https://gitter.im/publiclab/publiclab
> And do check out [code.publiclab.org](https://code.publiclab.org)
> Kindly close the issue :)

Done !!
