### ISSUE TITLE
migrate from Travis CI to Github Actions for automated tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#427]
We need to migrate from Travis CI to Github Actions and get those checks and tests running again! Just like we did here:

https://github.com/publiclab/leaflet-environmental-layers/pull/503

**Comment by YogeshSharma01** [comment]
Hi, @jywarren I would like to work on this.

**Comment by Swayamsvk** [comment]
Hi, @jywarren I am quite new to testing but I have tried my best please check this pr and tell me if anything else is required.

**Comment by Swayamsvk** [comment]
Actually, I have pushed the main branch accidentally and I have to revert all those changes but this is the exact copy of the previous pull request I have created a separate branch and pushed it. It may work now please check.And I am really sorry for my mistake.

**Comment by jywarren** [comment]
Hi, it's no problem, but I think due to the security issues i noted in #429, it's not running the checks. If you'd like, you can close your PR but I can open a new PR using your commits, so it's my security credentials... hopefully that would work!

**Comment by Swayamsvk** [comment]
ok I will close it

**Comment by jywarren** [comment]
trying in #435... sorry @Swayamsvk for the trouble here, i really am not sure what's going on!

**Comment by jywarren** [comment]
Oh wait!!! I found it! Here! https://github.com/Swayamsvk/community-toolbox/runs/1989504430?check_suite_focus=true

It ran on the forked repo, because https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

OK trying this...

**Comment by jywarren** [comment]
OK I was able to merge it at https://github.com/publiclab/community-toolbox/pull/435 and you got credit! Thank you so much!!!!

**Comment by Swayamsvk** [comment]
Thanks @jywarren
