### ISSUE TITLE
Navbar-formatting-fix

### ISSUE THREAD

**Issue by YogeshSharma01** [publiclab/community-toolbox#440]
The issue was introduced while resolving conflicts in PR https://github.com/publiclab/community-toolbox/pull/422.

These are the issues that have found out.

1. There is duplicate code for the navbar and the headings of FTO and Contributors sections.
2. CSS file had a missing parenthesis due to which the whole page was misaligned.

![image ](https://user-images.githubusercontent.com/51679200/111904173-7b516e00-8a6b-11eb-8641-37e478eb546e.png)

Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by YogeshSharma01** [comment]
Hi, @jywarren  I have fixed this please review https://github.com/publiclab/community-toolbox/pull/441

https://user-images.githubusercontent.com/51679200/111908621-ead15880-8a7f-11eb-9ad2-c3e971172e4f.mov

#441

**Comment by govindgoel** [comment]
Closing this as it has been fixed in #441
