### ISSUE TITLE
Fixing inconsistencies in dark mode

### ISSUE THREAD

**Issue by waridrox** [publiclab/community-toolbox#443]
### Please describe the problem (or idea)

Currently, when a user switches from light to dark theme, the images also lose their respective colors and turn into greyscale. This looks very inconsistent and dull, considering that on one hand we display the colors in light theme but on the other, we don't plus image section titled '**FTO Authors**' and '**first-timer-only issues**' simply inverts the color scheme to make things look more weird.

____
<img width="886" alt="Screenshot 2021-03-22 at 10 03 27 PM" src="https://user-images.githubusercontent.com/58583793/112024669-70c1d200-8b5a-11eb-862d-94a07e19c77d.png">

<img width="921" alt="Screenshot 2021-03-22 at 9 58 02 PM" src="https://user-images.githubusercontent.com/58583793/112023907-af0ac180-8b59-11eb-9667-67515e586545.png">

<img width="627" alt="Screenshot 2021-03-22 at 10 02 09 PM" src="https://user-images.githubusercontent.com/58583793/112024488-41ab6080-8b5a-11eb-98ad-cf3c8ea924bc.png">

### Please show us where to look

https://code.publiclab.org/

Possible solution could be to restore the colors in the dark theme as well so that a uniform consistency is maintained.

**Comment by govindgoel** [comment]
@waridrox I can't reproduce the issue, and it existed very earlier this has been already fixed.

**Comment by waridrox** [comment]
@govindgoel I believe it's still prevalent on the official website at https://code.publiclab.org/

**Comment by govindgoel** [comment]
@waridrox It seems fine

<img width="1143" alt="Screenshot 2021-03-27 at 10 41 00 PM" src="https://user-images.githubusercontent.com/52847415/112728489-8d407e80-8f4d-11eb-85dd-42de1f65b6e8.png">

<img width="1149" alt="Screenshot 2021-03-27 at 11 04 47 PM" src="https://user-images.githubusercontent.com/52847415/112729173-d8a85c00-8f50-11eb-8ada-fd99d397a16d.png">

**Comment by waridrox** [comment]
Yeah, now it seems to be fixed. 👍
