### ISSUE TITLE
Add language section link in the Navbar

### ISSUE THREAD

**Issue by YogeshSharma01** [publiclab/community-toolbox#446]
As we have our Navbar and Language section merged, but we need to connect them.
So, we need to add this language section in the navbar in the participants' tab.

 Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by YogeshSharma01** [comment]
Hi, @jywarren I have added the language section into the navbar 

https://user-images.githubusercontent.com/51679200/112632763-8f77df80-8e5e-11eb-93f3-9da1d738d6d7.mov

Please Review PR https://github.com/publiclab/community-toolbox/pull/447

**Comment by govindgoel** [comment]
Can close this as it is implemented in #447, just to check @YogeshSharma01 can you verify that the changes are working fine in dark mode as well.

**Comment by YogeshSharma01** [comment]
Hi, @govindgoel yes it is working fine in dark mode as well.
