### ISSUE TITLE
Fix charset character encoding value in embed and index file.

### ISSUE THREAD

**Issue by on2onyekachi** [publiclab/community-toolbox#548]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

value for the charset attribute is charset ='UTF8' in the meta tags

> What did you expect to see that you didn't?

I expected to see a value of charset='UTF-8' 

### Please show us where to look

[Index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html) and [embed.html](https://github.com/publiclab/community-toolbox/blob/main/examples/embed.html)

> This can help us diagnose the issue: 

```diff
- <meta http-equiv="content-type" content="text/html; charset=UTF8">
+ <meta http-equiv="content-type" content="text/html; charset=UTF-8">
$DIFF
```
****
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by TildaDares** [comment]
Thank you @on2onyekachi!!

**Comment by TildaDares** [comment]
Reserved for @archijaiswal for 24 hours!

**Comment by TildaDares** [comment]
I’m sorry I forgot to even ask if you wanted to work on this. If you’d like to work on this @on2onyekachi I’ll look for another issue for @archijaiswal

**Comment by on2onyekachi** [comment]
Okay @TildaDares . 

@archijaiswal can work on this.

**Comment by archijaiswal** [comment]
Thank you so much! I'm on it.
