### ISSUE TITLE
Move link tags from body to the head section in index.html

### ISSUE THREAD

**Issue by on2onyekachi** [publiclab/community-toolbox#550]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

`<link>` tags are placed in the `<body>` element. which still works fine and is permitted in the `<body>`. 

![Screenshot 2022-04-01 at 12 29 15](https://user-images.githubusercontent.com/66228222/161255113-4cdd7630-f6f7-41d6-8682-3d53ddcf7baf.png)

> What did you expect to see that you didn't?

However, I expected to see the `<link>` tag placed in the `<head>` element.  
![Screenshot 2022-04-01 at 12 39 27](https://user-images.githubusercontent.com/66228222/161256374-5f0f3c4d-8027-46e2-a69e-7379ae2589b1.png)

### Please show us where to look

[index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html)

### What's your PublicLab.org username? 
Thekachi

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by TildaDares** [comment]
Amazing @on2onyekachi!!! Do you think you could reformat this into an FTO? Thank you!!!

**Comment by on2onyekachi** [comment]
Thanks, @TildaDares . I will like to get busy with this.
