### ISSUE TITLE
Group similar inline style rule into demo.css

### ISSUE THREAD

**Issue by on2onyekachi** [publiclab/community-toolbox#564]
> What happened just before the problem occurred? Or what problem could this idea solve?

The same inline style rule can be grouped together: 
![Screenshot 2022-05-06 at 10 51 35](https://user-images.githubusercontent.com/66228222/167109273-0f6c32ad-a31f-4ca7-b307-f7da4d301488.png)
also 

```diff
-259: <div style="display: flex; justify-content: space-between">
+259: <div class='side-display'>

-330: <div style="display: flex; justify-content: space-between">
+330: <div class='side-display'>
```

> What did you expect to see that you didn't?

Into the sort-options,side-display class. 

![Screenshot 2022-05-06 at 11 31 22](https://user-images.githubusercontent.com/66228222/167115531-819e59cf-db6c-4691-8791-679270815041.png)

### Please show us where to look

[index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html)

### What's your PublicLab.org username?

[Thekachi](https://publiclab.org/profile/Thekachi)

****

**Comment by Devesh21700Kumar** [comment]
> > What happened just before the problem occurred? Or what problem could this idea solve?
> 
> The same inline style rule can be grouped together: ![Screenshot 2022-05-06 at 10 51 35](https://user-images.githubusercontent.com/66228222/167109273-0f6c32ad-a31f-4ca7-b307-f7da4d301488.png) also
> 
> ```diff
> -259: <div style="display: flex; justify-content: space-between">
> +259: <div class='side-display'>
> 
> -330: <div style="display: flex; justify-content: space-between">
> +330: <div class='side-display'>
> ```
> 
> > What did you expect to see that you didn't?
> 
> Into the sort-options,side-display class.
> 
> ![Screenshot 2022-05-06 at 11 31 22](https://user-images.githubusercontent.com/66228222/167115531-819e59cf-db6c-4691-8791-679270815041.png)
> 
> ### Please show us where to look
> [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html)
> 
> ### What's your PublicLab.org username?
> [Thekachi](https://publiclab.org/profile/Thekachi)
> 
> ## Thank you!

Okay
