### ISSUE TITLE
Show list of "contributors this week" separated out from "for all time"

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#57]
more soon! It'd be helpful to see recent activity 👍

**Comment by bkocsis3** [comment]
Hi, jywarren. I'd like to work on this for you. Can you tell me more about it? What files and webpages will be affected by this?

**Comment by gauravano** [comment]
@jywarren

**Comment by jywarren** [comment]
Hi all! The main demo will be affected; we'd like to be able to list
contributors by date of last activity in the list at the bottom of the
page. Are you able to see the code that drives this or would you like to
see links to some lines of code?

Thanks!!

**Comment by bkocsis3** [comment]
If you could send some links, that would be great!

**Comment by jywarren** [comment]
Maybe @Rishabh570 could help out here? I'm unfortunately about to board a plane! ✈️

**Comment by Rishabh570** [comment]
Hi @bkocsis3 

Here are some links to files that are affected,
- https://github.com/publiclab/community-toolbox/blob/master/index.html is the HTML file that is displayed when you visit `https://code.publiclab.org/`
- https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js file contains the logic which fetches the contributors from Github (it is the main driver behind data shown on the page)
- https://github.com/publiclab/community-toolbox/blob/master/src/ui.js is the file which inserts data to the page (index.html) which is shown to the user.

We use `github-api-simple` to fetch contributors, you can take a look at it also: `https://www.npmjs.com/package/github-api-simple`.

Hope this helps, looking for your PR :)
Thanks!!!

**Comment by Rishabh570** [comment]
I would like to work on this.

**Comment by bkocsis3** [comment]
Go for it. (: I've gotten too busy at work. ):
