### ISSUE TITLE
there is horizontal scrollbar at every dynamic info frame which is not used 

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/community-toolbox#571]
### What happened just before the problem occurred? Or what problem could this idea solve?
 Having not usable horizontal scrollbar is buggy and not good looking 

### What did you expect to see that you didn't?
   There is no use of horizontal scrollbar, we should remove it.

### Please show us where to look

https://code.publiclab.org/#r=plots2

![com_scrollbar](https://user-images.githubusercontent.com/59113935/167810104-638fa619-8993-4776-b81a-067a4e63c147.png)
![comm_scrollbar_2](https://user-images.githubusercontent.com/59113935/167810155-5868aa1d-8f13-4c76-b3bb-7de8007ecf81.png)
![com_scrollbar_3](https://user-images.githubusercontent.com/59113935/167810183-21fb2872-6205-4bbb-87b5-c8140ae3e234.png)

Hey @TildaDares @jywarren @cesswairimu, It is what I found, please tell me should we work on this issue or we can ignore it for now ?

Thank You

**Comment by TildaDares** [comment]
@RaviAnand111 I guess the issue is browser specific.

**Comment by RaviAnand111** [comment]
Hi @TildaDares,
 Ok I got it now Thank You,  
so should I close this issue ?

Thank You

**Comment by TildaDares** [comment]
Hi @RaviAnand111, we can. Thanks!!
