### ISSUE TITLE
Back to Top button is not static not fixed 

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/community-toolbox#576]
## What did you see and expected to happen 

1. The back to top button is static while it should have been fixed.
2. The icon in back to top button is not at center.
3. In mobile view the back to top button is covering some of the text, its position has to be moved a little to right.

### Please show us where to look

https://code.publiclab.org/

FireFox 
![btt-1](https://user-images.githubusercontent.com/59113935/168272893-3766b138-2f58-4d47-bd9d-2cdaa07242da.png)

https://user-images.githubusercontent.com/59113935/168275780-48798d82-ba91-4689-86f5-08cfcb194b4f.mp4

Chrome 
![btt-3-chrome](https://user-images.githubusercontent.com/59113935/168275978-0696b97c-bc8b-4a9c-9916-59f4b09324fa.png)

There are some inconsistencies between browsers as it seems the icon in chrome is in center but not in firefox.
But the problem of button not being fixed and covering up content in mobile view is same in both the browsers.

Hey @TildaDares @jywarren @cesswairimu, Can you please have a look and share your views. 
Thank You

**Comment by TildaDares** [comment]
Great catch @RaviAnand111. You can go ahead and open a PR for this. Thanks!

**Comment by radzhiv25** [comment]
Can i work on this issue 

> Great catch @RaviAnand111. You can go ahead and open a PR for this. Thanks!

**Comment by TildaDares** [comment]
Hi @radzhiv25, please go ahead. Thank you!

**Comment by vedant-z** [comment]
Hi @TildaDares may I try this?

**Comment by cesswairimu** [comment]
hi @vedant-z, you can go ahead, thanks

**Comment by vedant-z** [comment]
Hey @cesswairimu I figured out I need to tweak something in here.

![image](https://user-images.githubusercontent.com/93431609/201524700-cc5d5bd9-4d68-4d3a-82a9-598e751f95a1.png)

Something like changing the display to inline-block might work. Will you please suggest me something from your end?

**Comment by cesswairimu** [comment]
Hey @vedant-z, mmh maybe you can try putting it in the same div as footer? its a bit tough one as it seems to be working on for some browsers/OS and not for others. Were you able to replicate the issue on your end?  I haven't been able to replicate it on my end, I tried with chrome and firefox on Ubuntu 20.04, and chrome on android 11.

**Comment by aditi5050** [comment]
I would like to work on this issue shall I start working on it.

**Comment by cesswairimu** [comment]
hi @aditi5050, are you able to replicate the bug on your end? I don't see it on my end as I mentioned above https://github.com/publiclab/community-toolbox/issues/576#issuecomment-1322075767. If you are able to you can go ahead, thanks

**Comment by aditi5050** [comment]
@cesswairimu yes I think the issue has been solved, I would try working on some other issues 
I'm sorry for engaging your time

**Comment by cesswairimu** [comment]
No problem @aditi5050, we appreciate your interest and  we would love help your help on any other open issues. Sometimes some open issues are solved on other issues and we can only realized once we take a look again on the bug. Thanks all, closing this now.
