### ISSUE TITLE
Display more than 30 contributors

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#6]
In the bottom, Contributors listing, we seem to be getting only 30, and not the 100 we're requesting. 

https://publiclab.github.io/community-toolbox/

![screenshot 2017-10-25 at 10 47 03 am](https://user-images.githubusercontent.com/24359/32005377-2421d930-b972-11e7-81bf-d632251ea05f.png)

On this line we request 100 -- used in the `options` var:

https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L12

We use that options var here:

https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L34

But maybe we're not using the API correctly? The docs are at:

https://www.npmjs.com/package/github-api-simple

Looks like a little trial and error, and some API docs reading, would be helpful to solve this. 

Any assistance appreciated!!!

**Comment by rvben** [comment]
I just submitted a PR for this Issue.

**Comment by jywarren** [comment]
Completed! Thank you!!
