### ISSUE TITLE
Show a spinner icon till contributors list is not rendered

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#62]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html#L134) and [community-toolbox.js](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

**index.html**
```diff
+ <i class="fa fa-spinner fa-spin" id="spinner-icon"></i>
```

**community-toolbox.js**
At lines [87](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L87), [109](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L109), [126](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L126), [161](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L161) and [176](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L176), add the line shown below,

```diff
+ document.getElementById("spinner-icon").style.visibility = "hidden";
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
This one needs a link to a line of code, and then would make a great first-timers-only issue!!!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by Rishabh570** [comment]
Solving this issue includes doing the following changes shown below,

- Inside div having class `well contributors` in [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html#L134), add this line,
    `<i class="fa fa-spinner fa-spin"></i>`
    (outside of `<p>` tags)

- Now in [community-toolbox.js](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js), add code to hide spinner icon at lines
[87](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L87), [109](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L109), [126](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L126), [161](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L161) and [176](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L176)

as these are the lines after which data is rendered to the user.

**Comment by gauravano** [comment]
Hi @Rishabh570, please add your above comment with FTO template in issue body to make it a first-timer-issue. Thanks!

**Comment by Rishabh570** [comment]
@gauravano Please take a look :)

**Comment by radheyshyamjangid** [comment]
hello @Rishabh570  can i take this issue?

**Comment by Rishabh570** [comment]
@radheyshyamjangid Sure, go ahead!!
Also, you might want to visit https://code.publiclab.org/  for first-timer-issues and other useful information...
