### ISSUE TITLE
Change Readme.md link in index.html (First-timers-issue)

### ISSUE THREAD

**Issue by roshniRam** [publiclab/community-toolbox#67]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

Currently to Readme.md link directs user to plots2 repository. Therefore, to change it-

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html) in the [`community-toolbox`](https://github.com/publiclab/community-toolbox) repository (press the little pen Icon) and edit the line as shown below. 

```html
<div class="col-md-6">
    <p>If you're new, and looking to get involved, you're in the right place. Check out <a href="https://github.com/publiclab/plots2/blob/master/README.md">our README</a> to get started.</p>
```
![screenshot 55](https://user-images.githubusercontent.com/30633549/46871007-db309d00-ce4d-11e8-8246-67af80eb65b1.png)

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
Hi @roshniRam -- this is a great issue, and well formatted, thank you! Before marking it as a first-timers-only issue, can you paste the text you want this changed too, since your screenshot doesn't show it (it went off the side of the screen 😄 )

Thanks!

**Comment by vagita24** [comment]
can i take this issue?

**Comment by roshniRam** [comment]
Yeah sure, go for it @vagita24 😄

**Comment by jywarren** [comment]
Hi, @roshniRam just wanted to check if you could update the text you're asking this to be changed to, since the screenshot seems cut off?

Thanks!

You can also show this kind of thing in `diff` mode, like this:

```diff
- This line gets removed
+ This line gets added
```

You can write things like this like this:

![image](https://user-images.githubusercontent.com/24359/47260497-5adbee80-d482-11e8-832f-032cbc834259.png)

**Comment by debck** [comment]
I want to work on this issue. Please assign me

**Comment by jywarren** [comment]
No need to be assigned, actually! But please go ahead, we'd love your help!
