### ISSUE TITLE
Create FTO issue Template

### ISSUE THREAD

**Issue by starkblaze01** [publiclab/community-toolbox#71]
**Current Scenario:-**
We don't have any first-times-issue template for this repository.
 
**Deliverables:-**
Create this template and place it in https://github.com/publiclab/community-toolbox/tree/main/.github

**Reference:-**
https://github.com/publiclab/plots2/tree/master/.github

**Comment by starkblaze01** [comment]
@jywarren, please add a label to this issue. :)

**Comment by avsingh999** [comment]
@starkblaze01 I think this issue like this https://github.com/publiclab/plots2/issues/3685
thanks :)

**Comment by starkblaze01** [comment]
yeah! Thanks for pointing out.

**Comment by starkblaze01** [comment]
:) I have changed it for first-time issue template as it was not mentioned in publiclab/plots2#3685

**Comment by SidharthBansal** [comment]
@jywarren can you please add GCI-candidate label to this issue?

**Comment by jywarren** [comment]
Ah but actually it's been done here! https://github.com/publiclab/community-toolbox/blob/main/.github/first-timers-issue-template.md

Thank you all!
