### ISSUE TITLE
Add a section in the readme showing how to filter issues by labels and repo in the URL.

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#72]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## The Problem

When looking at [embed.html](https://github.com/publiclab/community-toolbox/blob/main/examples/embed.html), we have the option of looking for issues related to a particular repository and furthermore, we can filter issues by their labels. But it's not documented in the `Readme.md`.

## The Solution

Below are some examples of how to do it,

- `https://publiclab.github.io/community-toolbox/examples/embed.html#r=plots2` gives us all the issues of `plots2` repo.

- `https://publiclab.github.io/community-toolbox/examples/embed.html#r=all` gives us all the `first-timer-only` issues of all the repositories. (because default is first-timer-only issues)

- `https://publiclab.github.io/community-toolbox/examples/embed.html#r=all&l=help-wanted` gives us all the `help-wanted` issues of all the repositories. (`l` can be any label of choice).

We need to add a section in readme showing how to filter issues based on repo and labels...examples like above are to be written.

**Instance Count = 1**

**Comment by jywarren** [comment]
👍🏽

**Comment by dinaelhanan** [comment]
Done!
