### ISSUE TITLE
Add Facebook and Twitter icon at the footer

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/community-toolbox#77]
### Please describe the problem (or idea)
Visit https://code.publiclab.org/ and observe the functionality at the footer for other icons and add the same functionality for Facebook and Twitter icon.

**Facebook** :  https://www.facebook.com/PublicLab/

**Twitter** :  https://twitter.com/PublicLab?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> What happened just before the problem occurred? Or what problem could this idea solve?
![screenshot 248](https://user-images.githubusercontent.com/25260367/47264841-df3e7800-d53b-11e8-994f-ea98299281f8.png)

> What did you expect to see that you didn't?
![look](https://user-images.githubusercontent.com/25260367/47316355-8a4a5100-d664-11e8-9723-612016cf4721.PNG)

### Please show us where to look

https://code.publiclab.org/

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Version 70.0.3538.67 (Official Build) (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
@jywarren is it needed?
Should we add this to GCI task list?

**Comment by jywarren** [comment]
I think this is OK! I'd prefer they appear to the left of the existing
icons, though. Thanks!!!

**Comment by DakshGondaliya** [comment]
@jywarren, please review it again. I update the 2nd screenshot in the issue.
Is this ok?

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
