### ISSUE TITLE
Create a Scroll To Top Button

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/community-toolbox#80]
### Please describe the problem (or idea)
Create a button that will take the user to the top of the page when clicked on the button.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
![ezgif com-gif-to-mp4](https://user-images.githubusercontent.com/25260367/47320072-02694480-d66e-11e8-8dde-b120516a1d09.gif)

### Please show us where to look
https://code.publiclab.org/

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10, Google Chrome Version 70.0.3538.67 (Official Build) (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by DakshGondaliya** [comment]
@jywarren @SidharthBansal, please review this issue. 
Is it ok?

**Comment by Dhiraj240** [comment]
@DakshGondaliya Nope, you have to follow this [template](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md) so do the required changes and you are good to go.

**Comment by DakshGondaliya** [comment]
@Dhiraj240 thank you for review my issue, but this is not first timer only issue.It's only GCI candidate issue and I follow the ISSUE_TEMPLATE. md for this issue.

**Comment by rohan2599** [comment]
LGTM @jywarren @SidharthBansal please review

**Comment by DakshGondaliya** [comment]
@SidharthBansal please add gci-candidate and help-wanted labels

**Comment by SidharthBansal** [comment]
Published

**Comment by Dhiraj240** [comment]
@DakshGondaliya Oh, alright keep going.

**Comment by DakshGondaliya** [comment]
Thank you @SidharthBansal

**Comment by Paarmita** [comment]
@CodeSarthak You can follow the installation instructions to set up the project locally.https://github.com/publiclab/community-toolbox#install-instructions

**Comment by oorjitchowdhary** [comment]
Can I take this up? Also, I can't find a gci task for this..

**Comment by Harshithpabbati** [comment]
can i work on this??

**Comment by gauravano** [comment]
Hi @Harshithpabbati, sure. Go ahead!

**Comment by gauravano** [comment]
And, sorry @oorjitchowdhary for missing your comment, but I guess, you are no more interested in this issue. Thanks!

**Comment by Harshithpabbati** [comment]
I am done with it.How do i send pr to it any format???

**Comment by gauravano** [comment]
When you make the PR, you'll see the checklist in the body, try to follow
those rules. Thanks!

**Comment by rexagod** [comment]
Pinging @jywarren and @gauravano to close this (fixed in #140). Thanks @Harshithpabbati! :+1:

**Comment by gauravano** [comment]
Thanks @rexagod and @Harshithpabbati! Closing now.
