### ISSUE TITLE
Ability to set time range in queries: "weekly" + "monthly"

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#9]
We often want to look at a portrait of the community for a specific time range. The API and [options hash](https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L8) don't seem to have a time domain, however:

https://developer.github.com/v3/repos/
https://github.com/MichielvdVelde/github-api-simple

Either we need to find how to make a time-bounded API query, or we may be able to manually filter results by timestamp. 

Let's start with `getRepoContributors()`, since it's VERY useful to be able to see how many people contributed in a specific time range:

https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L32

**Comment by raghavmittal101** [comment]
I think that we can do this by filtering the commit log of a repo by time range and then find the number of unique contributors. Please let me know if you agree with me.

**Comment by jywarren** [comment]
Sure, that sounds great! So would you then make a request for the contributors based on their usernames, so 2 requests? Is there a way to batch request a set of user account records in a single query? 

We'd love to accept a PR from you if you're interested! Thanks a million!

**Comment by raghavmittal101** [comment]
I am using this https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository to get the list of commits and then use javascript to filter the commits by time range and return list of contributors.

I have written a code snippet in pure javascript but I don't know how to integrate that into your repo.

**Comment by jywarren** [comment]
Cool, can you link to a gist at gist.github.com? Thanks!

**Comment by raghavmittal101** [comment]
https://gist.github.com/raghavmittal101/0b4292e64d298fbc4213b29d221bd8dd

**Comment by jywarren** [comment]
This looks super. Can you use a pull request to add it to the `/src/` directory and add an "exports" statement as well, and we can take this one step at a time? Thanks!

https://github.com/publiclab/community-toolbox/blob/master/src/ui.js#L28-L31

Awesome!

**Comment by raghavmittal101** [comment]
I have created a new file in `/src/` directory called `getRepoContributors.js`. Let me know if that is fine.

**Comment by jywarren** [comment]
Hi, are you still interested in contributing a bit on this? we'd love to have your help!

**Comment by raghavmittal101** [comment]
Sure! How may I help you?

**Comment by jywarren** [comment]
Do you think we could integrate `getCommitsInRange()` into this file?

https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js

What do you think?

**Comment by jywarren** [comment]
@publiclab/reviewers if anyone is looking for a project, I think this one could amplify our work a lot in conjunction w #13 - so we can see recently welcoming people and thank/encourage them!

Could make a good fto perhaps!

**Comment by sk9331657** [comment]
@jywarren  Can I work on it??

**Comment by gauravano** [comment]
Hi @sk9331657, please proceed with the issue. Thanks!

**Comment by Rishabh570** [comment]
I would like to work on this. Actually, this [PR](https://github.com/publiclab/community-toolbox/pull/73) is related to this issue. That PR actually includes the functionality of showing active contributors last week, with a slight modification (after that PR gets merged) we can make it work for contributors last month.
A user would be able to query however he/she wants... :)

**Comment by jywarren** [comment]
Please! This would be great. Thanks!
