### ISSUE TITLE
Recent contributors - is it by repository?

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#92]
I went to https://code.publiclab.org/#r=image-sequencer, to see recent contributors for that project, and compared it to:

https://github.com/publiclab/image-sequencer/pulse/monthly
https://github.com/publiclab/image-sequencer/pulse/weekly

I'm not sure if it's pulling recent contributors for all of plots, though? 

![image](https://user-images.githubusercontent.com/24359/48316410-4c7c8080-e5b1-11e8-961e-ee192eb0c65c.png)

```
@pabisovsky, @ajzliu, @Rishabh570, @radheyshyamjangid, @aashna27, @jywarren, @Radhikadua123, @icarito, @moogwol, @dependabot[bot], @shubhscoder, @cesswairimu, @samyuravikumar, @slasher17, @CoderJolly, @mrtmrtmlck, @junhouse, @narnt, @hydro-m, @kevinzluo, @romanrodriguez, @love-opensource
```

Just checking! @Rishabh570 this is such a great feature - i was going to ask recent contributors if they'd like to take up some new bugs and feature requests. It's great to be able to have this level of understanding of a growing community 😄 Your work is really helping us grow!

**Comment by jywarren** [comment]
I think perhaps the list of contributors is being shown for /all/
repositories across publiclab, no just for the one I wanted to see,
"image-sequencer". Maybe Rishabh can take a look at this to clarify? But no
big rush!

**Comment by Rishabh570** [comment]
Yes, that's true...currently, the data is being fetched from the top 10 most active repos. It is not designed to get the recent contributors of a particular repo...
If that's needed, I would love to work on it :)

**Comment by jywarren** [comment]
If you're interested, that would be wonderful! Thanks!!

**Comment by Rishabh570** [comment]
Okay, I'll do it...its gonna restructure a chunk of code though :thought_balloon:

**Comment by jywarren** [comment]
well, i trust your understanding of the code... i wonder, do you think we
should come up with a more modular system that can accommodate this usage?

**Comment by Rishabh570** [comment]
Yeah, I also agree...the codebase is getting bigger and complex...what would you suggest for this?

**Comment by jywarren** [comment]
We could think about separating along an MVC model, where data is fetched and stored, and we have view templates separately, so we can query the storage system based on some parameters based on the use case, then use the templates to format them for insertion into the page. Controller code could interpret the URL and coordinate this all.

We could alternatively consider a bigger project to use a system like React or something instead of building our own MVC. But i'm not that familiar with those systems...

Brainstorming here! Take a look at least at the organizational principles of another more complex library like https://github.com/publiclab/plotsbot or https://github.com/publiclab/image-sequencer... image sequencer has a string interpreter (routing) and a UI, but the base functions are abstract. 

Hmm. Let's ponder a bit!

**Comment by Rishabh570** [comment]
@jywarren I'm thinking of using React (for frontend), Redux (for state management in react), express.js framework (for backend) and MongoDB for DB...it will be following MVC pattern, having a controller layer talking to the database and serving it to React for front-end and redux will manage states (data coming from DB will be stored in react states)
If you allow, I would love to work on this...It will take me a week or two to do the scaffolds though...

**Comment by jywarren** [comment]
Hmm, but would we be able to still do this as a client side application?

**Comment by Rishabh570** [comment]
Hi @jywarren, Do we want it to be just a pure client-side project...? If that's the case, I would look for another way around. I also saw `image-sequencer`, it's much bigger than this project...are we looking for something like that?
I am looking around for the various way to do this...need your help about which stack to go with :)

**Comment by jywarren** [comment]
I think it is ideal that it be purely client-side, as then people can run
it in the gh-pages system. We don't necessarily need to adopt a whole new
stack -- maybe we just need to start managing one portion in a more
structured way, like separating the views from the logic, for example.
Image sequencer is a good example where the UI logic is very separate from
the back-end image processing, and a standardized "module" format has
allowed for powerful features but within strict conventions and rules.

**Comment by Rishabh570** [comment]
Okay, so we need a separate folder that contains all the data fetching, another one containing views...right?

**Comment by jywarren** [comment]
Yes, you could have one called /api/, for the code to fetch the data, maybe
one called storage, one called ui? And clear relationships between them. We
might decide to use a standard component or library for the storage, right?
And decide on a standard format for the stored items. Could be a db-like
layer over localstorage... does MongoDB do something like that?

**Comment by Rishabh570** [comment]
> Could be a db-like
layer over localstorage

Hmm, I guess IndexedDB does that, never used that though...I'll look for its tutorials...
Yes, `storage` for code interacting with storage and `ui` for code interacting with UI would be a clean and understandable structure...
Once, I figure out the database to use, I'll share the project structure with you....once we decide that, I'll start working on it :)

**Comment by Rishabh570** [comment]
Hi @jywarren, I've looked at some sample code in order to understand how indexedDB work...I guess it is the right/appropriate choice for storage (as an aside, it can store objects also without converting them to string)...
we can have our project structure like so,

![screenshot from 2018-11-23 22-11-45](https://user-images.githubusercontent.com/25483260/48953743-ddb60480-ef6c-11e8-85a5-49e55ed6867e.png)

Here, `scripts` folder will contain the main script that will be main entry point, that will call `utils` for the helper functions to do stuff (another reason is to make main script a.k.a `community-toolbox.js` clean and short), then those helper functions (with intentions to manipulate the data stored) will call the `controller` which will be interacting with the `models` ( although models will be containing the ultimate code that will affect the data stored, controller is needed to pass in some custom inputs as arguments to model functions that we want the model to add or update etc.)...

_index.html_ can be at the root of project folder, I'm not sure about that...will work in either way I guess...

What do you think?

**Comment by jywarren** [comment]
This sounds great! I like it a lot! What do you think the data format will
be to store with -- pretty much as GitHub API returns it? Plus, perhaps,
the timestamp it was fetched?

**Comment by Rishabh570** [comment]
@jywarren We can store everything in the form of key-value pairs...so we will store all the data returned from Github API without any adjustments (as an object) and timestamps in strings...

**Comment by Rishabh570** [comment]
Hi @jywarren I've completed the contributors part, now it fetches contributors of all (top 20) repos & saves it in the database in the beginning of page load so that any request in the future is served from the database (database refreshes everyday)...Here is a working GIF,

![issues_92_2](https://user-images.githubusercontent.com/25483260/49222218-4a178480-f401-11e8-9dae-45144ad4dead.gif)

Now I'll work on `Recent Contributors` part...

**Comment by Rishabh570** [comment]
BTW It doesn't fetch data from 20 repos in the GIF because I was short on API quota at the time I was recording this :)

**Comment by jywarren** [comment]
Wow, do you have a PR open? fantastic work on this, very cool! 

If there's a "fetch()" method we can actually monitor the API usage by looking at last fetched data in the database, and initiate a new fetch as soon as API quote re-ups... cool!

Will we want to filter or merge the requests in any way after requesting, or are we just using the most recent complete fetch? If we filter or standardize and de-duplicate the API response, we can do partial updates, which may help with our API quota too. 

This is really cool. Perhaps we need to start looking at the code itself in a PR. Also to be careful to do only one major structural change at a time, so we don't break things (at least not too quickly 😄 )

Great work!

**Comment by Rishabh570** [comment]
@jywarren I've open a WIP PR for it #107 
Please take a look :)
